<#
Generate FunctionReference.md by scanning PowerShell source files for function declarations
and extracting nearby comment blocks as short descriptions.

Usage:
  pwsh -NoProfile -ExecutionPolicy Bypass -File .\tools\generate_function_docs.ps1

#>
Param(
    [string]$RepoRoot = (Split-Path -Parent $PSScriptRoot),
    [string]$OutFile = "$PSScriptRoot\..\docs\FunctionReference.md"
)

Write-Host "Scanning repository: $RepoRoot"

function Get-PrecedingCommentBlock($text, $startIndex) {
    # Return nearest contiguous comment block (<# ... #> or lines starting with #) immediately above the function
    $before = $text.Substring(0, $startIndex)
    # Try block comment
    $blockPattern = '(?s)<#(.*?)#>\s*$'
    $m = [regex]::Match($before, $blockPattern)
    if ($m.Success) { return $m.Groups[1].Value.Trim() }

    # Fallback: collect contiguous '#' lines from the end
    $lines = $before -split "\r?\n"
    $descLines = @()
    for ($i = $lines.Length - 1; $i -ge 0; $i--) {
        $line = $lines[$i]
        if ($line -match '^[ \t]*#') {
            $descLines += ($line -replace '^[ \t]*#\s?', '')
        } elseif ($line -match '^[ \t]*$') {
            # stop on blank line between comments and function
            if ($descLines.Count -gt 0) { break }
            else { continue }
        } else { break }
    }
    if ($descLines.Count -gt 0) { return ($descLines | Select-Object -Last 50 | [array]::Reverse; ($descLines -join "`n")) -join "`n" }
    return ''
}

function Get-Signature($text, $matchIndex) {
    # Grab the function declaration line and any following param block up to the closing ')'
    $snippet = $text.Substring($matchIndex, [Math]::Min(400, $text.Length - $matchIndex))
    $lines = $snippet -split "\r?\n"
    $sigLines = @()
    # first line
    $sigLines += $lines[0].Trim()
    # if next lines include 'param(', capture until matching ')'
    if ($snippet -match "(?s)param\s*\(") {
        $paramText = ''
        $open = 0
        foreach ($l in $lines[1..($lines.Length-1)]) {
            $paramText += "$l`n"
            $open += ([regex]::Matches($l, '\(')).Count
            $open -= ([regex]::Matches($l, '\)')).Count
            if ($open -le 0) { break }
        }
        if ($paramText) { $sigLines += $paramText.Trim() }
    }
    return ($sigLines -join " `n")
}

$files = Get-ChildItem -Path $RepoRoot -Recurse -Include *.ps1,*.psm1 -File -ErrorAction SilentlyContinue | Where-Object { $_.FullName -notmatch '\\.git\\' -and $_.FullName -notmatch '\\docs\\' -and $_.FullName -notmatch '\\tools\\' }

$entries = @()
foreach ($f in $files) {
    try {
        $text = Get-Content -Raw -LiteralPath $f.FullName -ErrorAction Stop
    } catch { continue }

    $pattern = '(?m)^[ \t]*function[ \t]+([A-Za-z0-9_\-]+)\b.*'
    $matches = [regex]::Matches($text, $pattern)
    foreach ($m in $matches) {
        $name = $m.Groups[1].Value
        $sig = Get-Signature $text $m.Index
        $desc = Get-PrecedingCommentBlock $text $m.Index
        $entry = [PSCustomObject]@{
            Name = $name
            Signature = $sig
            Description = if ($desc) { $desc.Split("`n")[0].Trim() } else { '' }
            Source = $f.FullName
        }
        $entries += $entry
    }
}

# Deduplicate by name (keep first)
$byName = @{}
foreach ($e in $entries) {
    if (-not $byName.ContainsKey($e.Name)) { $byName[$e.Name] = $e }
}

$out = @()
$out += "# Function Reference (auto-generated)"
$out += ''
$out += "This file was generated by `tools/generate_function_docs.ps1`. Run the script to refresh the contents." 
$out += ''
foreach ($name in ($byName.Keys | Sort-Object)) {
    $e = $byName[$name]
    $out += "## $($e.Name)"
    $out += ''
    if ($e.Signature) {
        $out += "Signature:"
        $out += ''
        $out += '```powershell'
        $out += $e.Signature
        $out += '```'
        $out += ''
    }
    if ($e.Description) {
        $out += "Short description:"
        $out += ''
        $out += $e.Description
        $out += ''
    }
    $out += "Source: $($e.Source)"
    $out += ''
}

Write-Host "Writing output to $OutFile"
Set-Content -LiteralPath $OutFile -Value ($out -join "`n") -Encoding UTF8
Write-Host "Done. Found $($byName.Count) unique functions."
